
services:
  xcom-ui:
    build:
      context: ./bridge
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  # Web UI
      - "8765:8765"  # WebSocket bridge
    volumes:
      - ./web/app:/app/web  # Mount web files for easy development
      - /dev:/dev           # Give access to USB devices
    environment:
      - PYTHONUNBUFFERED=1  # Show Python logs immediately
      - BRIDGE_ARGS=${BRIDGE_ARGS:-"--ws-port 8765"}  # Bridge arguments from start script
    # Make sure container keeps running and restarts if it fails
    restart: unless-stopped
    privileged: true        # Needed for USB device access